spring.application.name=user_service

server.port=9898

# Database config
spring.datasource.url=jdbc:postgresql://pg-1d71051-vaghasiyajay2002-d5c6.h.aivencloud.com:10385/projectdataset
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ylfwI76usKyXN9W1tSL

# Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SMTP Server Configuration for Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vaghasiyajaykumar251@gmail.com
spring.mail.password=ipdycmpwunjwafnw
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# File upload config
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1020MB
file.upload-dir=F:/2.Royal/Spring - Tejas Sir/user_service/src/main/webapp/user_profile_pic/